server:
  port: 8080
  compression.enabled: true

spring:
  datasource:
    url: jdbc:mysql://database:3306/compute?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: deadl1ne
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitmq
    password: rabbitmq

logging:
  level:
    org.hibernate.SQL: DEBUG

app:
  jwt-secret: JWTSuperSecretKey
  jwt-expiration-in-ms: 604800000
  instance-name: ${INSTANCE_NAME:compute-unknown}
